#这是开发环境 配置 yml
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/learn_security?characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=GMT%2B8
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
    #type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录，500ms 以上为慢sql
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
      useGlobalDataSourceStat: true                   # 合并多个DruidDataSource的监控数据
      # Druid WebStatFilter配置
      web-stat-filter:
        enabled: true
        url-pattern: "/*"
        exclusions: '*.gif,*.png,*.jpg,*.html,*.js,*.css,*.ico,/druid/*'
      # Druid StatViewServlet配置
      stat-view-servlet:
        enabled: true
        # IP白名单(没有配置或者为空，则允许所有访问)
        allow: 127.0.0.1
        url-pattern: "/druid/*"
        reset-enable: true  #HTML页面上的“Reset All”功能
        login-username: admin
        login-password: admin


management:
  server:
    port: 8080
    address: 127.0.0.1
  endpoints:
    web:
      base-path: '/springManage'     # url 前缀
      exposure:
        include: '*'    # 开放所有 端点

server:
  port: 8080

security:
  oauth2:
    client:
      client-id: lym
      client-secret: demo
